/**
 * Mock Shopify Data for Testing
 * Used when Admin API token is not available
 */

export const MOCK_CUSTOMERS = [
  {
    id: 'gid://shopify/Customer/1001',
    legacyResourceId: '1001',
    email: 'sarah.johnson@example.com',
    firstName: 'Sarah',
    lastName: 'Johnson',
    phone: '+1 (555) 123-4567',
    ordersCount: 5,
    totalSpent: '249.95',
    totalSpentCurrency: 'USD',
    createdAt: '2024-08-15T10:30:00Z',
    updatedAt: '2025-01-20T14:22:00Z',
    state: 'ENABLED',
    tags: ['vip', 'repeat-customer'],
    defaultAddress: {
      address1: '123 Main Street',
      city: 'Austin',
      province: 'Texas',
      country: 'United States',
      zip: '78701',
    },
    note: 'Loves personalized books for her kids',
  },
  {
    id: 'gid://shopify/Customer/1002',
    legacyResourceId: '1002',
    email: 'michael.chen@example.com',
    firstName: 'Michael',
    lastName: 'Chen',
    phone: '+1 (555) 234-5678',
    ordersCount: 3,
    totalSpent: '149.97',
    totalSpentCurrency: 'USD',
    createdAt: '2024-10-02T08:15:00Z',
    updatedAt: '2025-01-18T09:45:00Z',
    state: 'ENABLED',
    tags: ['new-customer'],
    defaultAddress: {
      address1: '456 Oak Avenue',
      city: 'San Francisco',
      province: 'California',
      country: 'United States',
      zip: '94102',
    },
    note: null,
  },
  {
    id: 'gid://shopify/Customer/1003',
    legacyResourceId: '1003',
    email: 'emma.wilson@example.com',
    firstName: 'Emma',
    lastName: 'Wilson',
    phone: '+1 (555) 345-6789',
    ordersCount: 8,
    totalSpent: '399.92',
    totalSpentCurrency: 'USD',
    createdAt: '2024-05-20T16:00:00Z',
    updatedAt: '2025-01-22T11:30:00Z',
    state: 'ENABLED',
    tags: ['vip', 'gift-buyer', 'repeat-customer'],
    defaultAddress: {
      address1: '789 Elm Street',
      city: 'New York',
      province: 'New York',
      country: 'United States',
      zip: '10001',
    },
    note: 'Orders for grandchildren - always includes gift wrapping',
  },
  {
    id: 'gid://shopify/Customer/1004',
    legacyResourceId: '1004',
    email: 'james.taylor@example.com',
    firstName: 'James',
    lastName: 'Taylor',
    phone: '+1 (555) 456-7890',
    ordersCount: 1,
    totalSpent: '49.99',
    totalSpentCurrency: 'USD',
    createdAt: '2025-01-10T12:00:00Z',
    updatedAt: '2025-01-10T12:00:00Z',
    state: 'ENABLED',
    tags: ['new-customer'],
    defaultAddress: {
      address1: '321 Pine Road',
      city: 'Seattle',
      province: 'Washington',
      country: 'United States',
      zip: '98101',
    },
    note: null,
  },
  {
    id: 'gid://shopify/Customer/1005',
    legacyResourceId: '1005',
    email: 'olivia.martinez@example.com',
    firstName: 'Olivia',
    lastName: 'Martinez',
    phone: '+1 (555) 567-8901',
    ordersCount: 12,
    totalSpent: '599.88',
    totalSpentCurrency: 'USD',
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2025-01-23T15:00:00Z',
    state: 'ENABLED',
    tags: ['vip', 'loyalty-program', 'repeat-customer'],
    defaultAddress: {
      address1: '654 Maple Lane',
      city: 'Chicago',
      province: 'Illinois',
      country: 'United States',
      zip: '60601',
    },
    note: 'Teacher - bulk orders for classroom',
  },
];

export const MOCK_ORDERS = [
  {
    id: 'gid://shopify/Order/2001',
    legacyResourceId: '2001',
    name: '#TMT-1001',
    email: 'sarah.johnson@example.com',
    phone: '+1 (555) 123-4567',
    createdAt: '2025-01-20T14:22:00Z',
    updatedAt: '2025-01-21T10:00:00Z',
    processedAt: '2025-01-20T14:22:00Z',
    cancelledAt: null,
    closedAt: null,
    displayFinancialStatus: 'PAID',
    displayFulfillmentStatus: 'IN_PROGRESS',
    confirmed: true,
    test: false,
    totalPrice: '49.99',
    totalPriceCurrency: 'USD',
    subtotalPrice: '49.99',
    totalTax: '0.00',
    totalShipping: '0.00',
    customer: {
      id: 'gid://shopify/Customer/1001',
      email: 'sarah.johnson@example.com',
      firstName: 'Sarah',
      lastName: 'Johnson',
    },
    shippingAddress: {
      firstName: 'Sarah',
      lastName: 'Johnson',
      address1: '123 Main Street',
      city: 'Austin',
      province: 'Texas',
      country: 'United States',
      zip: '78701',
    },
    lineItems: [
      {
        id: 'gid://shopify/LineItem/3001',
        title: 'The Adventure of [Child Name]',
        quantity: 1,
        price: '49.99',
        sku: 'TMT-ADV-001',
        variantTitle: 'Hardcover',
        customAttributes: [
          { key: 'Child Name', value: 'Emily' },
          { key: 'Age', value: '5' },
        ],
      },
    ],
    fulfillments: [
      {
        id: 'gid://shopify/Fulfillment/4001',
        status: 'IN_PROGRESS',
        createdAt: '2025-01-21T10:00:00Z',
        trackingInfo: [
          {
            company: 'USPS',
            number: '9400111899223456789012',
            url: 'https://tools.usps.com/go/TrackConfirmAction?tLabels=9400111899223456789012',
          },
        ],
      },
    ],
    note: 'Please include gift wrapping',
    tags: ['gift', 'priority'],
  },
  {
    id: 'gid://shopify/Order/2002',
    legacyResourceId: '2002',
    name: '#TMT-1002',
    email: 'michael.chen@example.com',
    phone: '+1 (555) 234-5678',
    createdAt: '2025-01-18T09:45:00Z',
    updatedAt: '2025-01-22T16:30:00Z',
    processedAt: '2025-01-18T09:45:00Z',
    cancelledAt: null,
    closedAt: '2025-01-22T16:30:00Z',
    displayFinancialStatus: 'PAID',
    displayFulfillmentStatus: 'FULFILLED',
    confirmed: true,
    test: false,
    totalPrice: '49.99',
    totalPriceCurrency: 'USD',
    subtotalPrice: '49.99',
    totalTax: '4.12',
    totalShipping: '5.99',
    customer: {
      id: 'gid://shopify/Customer/1002',
      email: 'michael.chen@example.com',
      firstName: 'Michael',
      lastName: 'Chen',
    },
    shippingAddress: {
      firstName: 'Michael',
      lastName: 'Chen',
      address1: '456 Oak Avenue',
      city: 'San Francisco',
      province: 'California',
      country: 'United States',
      zip: '94102',
    },
    lineItems: [
      {
        id: 'gid://shopify/LineItem/3002',
        title: 'My First ABC Adventure',
        quantity: 1,
        price: '49.99',
        sku: 'TMT-ABC-001',
        variantTitle: 'Softcover',
        customAttributes: [
          { key: 'Child Name', value: 'Lily' },
        ],
      },
    ],
    fulfillments: [
      {
        id: 'gid://shopify/Fulfillment/4002',
        status: 'SUCCESS',
        createdAt: '2025-01-20T14:00:00Z',
        trackingInfo: [
          {
            company: 'FedEx',
            number: '794644790299',
            url: 'https://www.fedex.com/fedextrack/?trknbr=794644790299',
          },
        ],
      },
    ],
    note: null,
    tags: [],
  },
  {
    id: 'gid://shopify/Order/2003',
    legacyResourceId: '2003',
    name: '#TMT-1003',
    email: 'emma.wilson@example.com',
    phone: '+1 (555) 345-6789',
    createdAt: '2025-01-22T11:30:00Z',
    updatedAt: '2025-01-22T11:30:00Z',
    processedAt: '2025-01-22T11:30:00Z',
    cancelledAt: null,
    closedAt: null,
    displayFinancialStatus: 'PAID',
    displayFulfillmentStatus: 'UNFULFILLED',
    confirmed: true,
    test: false,
    totalPrice: '99.98',
    totalPriceCurrency: 'USD',
    subtotalPrice: '99.98',
    totalTax: '8.25',
    totalShipping: '0.00',
    customer: {
      id: 'gid://shopify/Customer/1003',
      email: 'emma.wilson@example.com',
      firstName: 'Emma',
      lastName: 'Wilson',
    },
    shippingAddress: {
      firstName: 'Emma',
      lastName: 'Wilson',
      address1: '789 Elm Street',
      city: 'New York',
      province: 'New York',
      country: 'United States',
      zip: '10001',
    },
    lineItems: [
      {
        id: 'gid://shopify/LineItem/3003',
        title: 'The Birthday Surprise',
        quantity: 2,
        price: '49.99',
        sku: 'TMT-BDAY-001',
        variantTitle: 'Hardcover',
        customAttributes: [
          { key: 'Child Name', value: 'Jack' },
          { key: 'Age', value: '7' },
        ],
      },
    ],
    fulfillments: [],
    note: 'Two copies - one for each grandchild',
    tags: ['gift', 'bulk'],
  },
  {
    id: 'gid://shopify/Order/2004',
    legacyResourceId: '2004',
    name: '#TMT-1004',
    email: 'james.taylor@example.com',
    phone: '+1 (555) 456-7890',
    createdAt: '2025-01-10T12:00:00Z',
    updatedAt: '2025-01-15T09:00:00Z',
    processedAt: '2025-01-10T12:00:00Z',
    cancelledAt: null,
    closedAt: '2025-01-15T09:00:00Z',
    displayFinancialStatus: 'PAID',
    displayFulfillmentStatus: 'FULFILLED',
    confirmed: true,
    test: false,
    totalPrice: '49.99',
    totalPriceCurrency: 'USD',
    subtotalPrice: '49.99',
    totalTax: '4.37',
    totalShipping: '5.99',
    customer: {
      id: 'gid://shopify/Customer/1004',
      email: 'james.taylor@example.com',
      firstName: 'James',
      lastName: 'Taylor',
    },
    shippingAddress: {
      firstName: 'James',
      lastName: 'Taylor',
      address1: '321 Pine Road',
      city: 'Seattle',
      province: 'Washington',
      country: 'United States',
      zip: '98101',
    },
    lineItems: [
      {
        id: 'gid://shopify/LineItem/3004',
        title: 'Space Explorer Adventure',
        quantity: 1,
        price: '49.99',
        sku: 'TMT-SPACE-001',
        variantTitle: 'Hardcover',
        customAttributes: [
          { key: 'Child Name', value: 'Noah' },
        ],
      },
    ],
    fulfillments: [
      {
        id: 'gid://shopify/Fulfillment/4004',
        status: 'SUCCESS',
        createdAt: '2025-01-12T11:00:00Z',
        trackingInfo: [
          {
            company: 'UPS',
            number: '1Z999AA10123456784',
            url: 'https://www.ups.com/track?tracknum=1Z999AA10123456784',
          },
        ],
      },
    ],
    note: null,
    tags: [],
  },
  {
    id: 'gid://shopify/Order/2005',
    legacyResourceId: '2005',
    name: '#TMT-1005',
    email: 'olivia.martinez@example.com',
    phone: '+1 (555) 567-8901',
    createdAt: '2025-01-23T15:00:00Z',
    updatedAt: '2025-01-23T15:00:00Z',
    processedAt: '2025-01-23T15:00:00Z',
    cancelledAt: null,
    closedAt: null,
    displayFinancialStatus: 'PENDING',
    displayFulfillmentStatus: 'UNFULFILLED',
    confirmed: true,
    test: false,
    totalPrice: '249.95',
    totalPriceCurrency: 'USD',
    subtotalPrice: '249.95',
    totalTax: '20.62',
    totalShipping: '0.00',
    customer: {
      id: 'gid://shopify/Customer/1005',
      email: 'olivia.martinez@example.com',
      firstName: 'Olivia',
      lastName: 'Martinez',
    },
    shippingAddress: {
      firstName: 'Olivia',
      lastName: 'Martinez',
      address1: '654 Maple Lane',
      city: 'Chicago',
      province: 'Illinois',
      country: 'United States',
      zip: '60601',
    },
    lineItems: [
      {
        id: 'gid://shopify/LineItem/3005',
        title: 'Classroom Reading Set',
        quantity: 5,
        price: '49.99',
        sku: 'TMT-CLASS-001',
        variantTitle: 'Softcover Bundle',
        customAttributes: [
          { key: 'Class Name', value: 'Mrs. Martinez 2nd Grade' },
        ],
      },
    ],
    fulfillments: [],
    note: 'Bulk order for classroom - needs by Feb 1st',
    tags: ['bulk', 'education', 'priority'],
  },
];

export const MOCK_PRODUCTS = [
  {
    id: 'gid://shopify/Product/5001',
    title: 'The Adventure of [Child Name]',
    handle: 'adventure-personalized-book',
    description: 'A magical adventure story where your child is the hero! Personalized with their name throughout the story.',
    productType: 'Personalized Book',
    tags: ['adventure', 'personalized', 'bestseller'],
    priceRange: {
      minPrice: '49.99',
      maxPrice: '59.99',
      currency: 'USD',
    },
    images: [
      { url: 'https://via.placeholder.com/400x400?text=Adventure+Book', altText: 'Adventure Book Cover' },
    ],
    variants: [
      { id: 'gid://shopify/ProductVariant/6001', title: 'Softcover', price: '49.99', available: true },
      { id: 'gid://shopify/ProductVariant/6002', title: 'Hardcover', price: '59.99', available: true },
    ],
  },
  {
    id: 'gid://shopify/Product/5002',
    title: 'My First ABC Adventure',
    handle: 'abc-adventure-book',
    description: 'Learn the alphabet with your child as the star! Each letter features personalized illustrations.',
    productType: 'Educational Book',
    tags: ['educational', 'alphabet', 'ages-2-5'],
    priceRange: {
      minPrice: '44.99',
      maxPrice: '54.99',
      currency: 'USD',
    },
    images: [
      { url: 'https://via.placeholder.com/400x400?text=ABC+Book', altText: 'ABC Book Cover' },
    ],
    variants: [
      { id: 'gid://shopify/ProductVariant/6003', title: 'Softcover', price: '44.99', available: true },
      { id: 'gid://shopify/ProductVariant/6004', title: 'Hardcover', price: '54.99', available: true },
    ],
  },
  {
    id: 'gid://shopify/Product/5003',
    title: 'The Birthday Surprise',
    handle: 'birthday-surprise-book',
    description: 'The perfect birthday gift! A personalized story celebrating your child\'s special day.',
    productType: 'Personalized Book',
    tags: ['birthday', 'personalized', 'gift'],
    priceRange: {
      minPrice: '49.99',
      maxPrice: '59.99',
      currency: 'USD',
    },
    images: [
      { url: 'https://via.placeholder.com/400x400?text=Birthday+Book', altText: 'Birthday Book Cover' },
    ],
    variants: [
      { id: 'gid://shopify/ProductVariant/6005', title: 'Softcover', price: '49.99', available: true },
      { id: 'gid://shopify/ProductVariant/6006', title: 'Hardcover', price: '59.99', available: true },
    ],
  },
  {
    id: 'gid://shopify/Product/5004',
    title: 'Space Explorer Adventure',
    handle: 'space-explorer-book',
    description: 'Blast off into space with this exciting personalized adventure among the stars!',
    productType: 'Personalized Book',
    tags: ['space', 'adventure', 'personalized', 'ages-5-10'],
    priceRange: {
      minPrice: '49.99',
      maxPrice: '59.99',
      currency: 'USD',
    },
    images: [
      { url: 'https://via.placeholder.com/400x400?text=Space+Book', altText: 'Space Book Cover' },
    ],
    variants: [
      { id: 'gid://shopify/ProductVariant/6007', title: 'Softcover', price: '49.99', available: true },
      { id: 'gid://shopify/ProductVariant/6008', title: 'Hardcover', price: '59.99', available: true },
    ],
  },
  {
    id: 'gid://shopify/Product/5005',
    title: 'Classroom Reading Set',
    handle: 'classroom-reading-set',
    description: 'Perfect for teachers! A set of 5 personalized books for classroom reading.',
    productType: 'Bundle',
    tags: ['education', 'bulk', 'classroom'],
    priceRange: {
      minPrice: '199.99',
      maxPrice: '249.99',
      currency: 'USD',
    },
    images: [
      { url: 'https://via.placeholder.com/400x400?text=Classroom+Set', altText: 'Classroom Set' },
    ],
    variants: [
      { id: 'gid://shopify/ProductVariant/6009', title: 'Softcover Bundle', price: '199.99', available: true },
      { id: 'gid://shopify/ProductVariant/6010', title: 'Hardcover Bundle', price: '249.99', available: true },
    ],
  },
];

export const MOCK_STATS = {
  totalOrders: 127,
  totalRevenue: 6349.73,
  totalCustomers: 89,
  averageOrderValue: 50.00,
  pendingOrders: 12,
  fulfilledOrders: 108,
  cancelledOrders: 7,
  newCustomersThisMonth: 23,
  returningCustomerRate: 0.42,
};

export function getMockCustomerByEmail(email: string) {
  return MOCK_CUSTOMERS.find(c => c.email.toLowerCase() === email.toLowerCase()) || null;
}

export function getMockCustomerById(id: string) {
  return MOCK_CUSTOMERS.find(c => c.id === id || c.legacyResourceId === id) || null;
}

export function getMockOrderById(id: string) {
  return MOCK_ORDERS.find(o => o.id === id || o.legacyResourceId === id || o.name === id) || null;
}

export function getMockOrdersByEmail(email: string) {
  return MOCK_ORDERS.filter(o => o.email.toLowerCase() === email.toLowerCase());
}

export function getMockOrdersByCustomerId(customerId: string) {
  return MOCK_ORDERS.filter(o => o.customer.id === customerId);
}
